services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    restart: always
    environment:
      - PORT=5000

  web:
    build:
      context: ./web
    ports:
      - "3000:3000"
    restart: always

  db:
    image: postgres:17
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
   pgdata:
