services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    restart: always
    environment:
      - PORT=5000

  web:
    build:
      context: ./web
    ports:
      - "3000:3000"
    restart: always
