name: teal

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [server, web, cli]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js for web and server
        if: matrix.project != 'cli'
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Go for CLI
        if: matrix.project == 'cli'
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install & Run CLI
        if: matrix.project == 'cli'
        working-directory: cli
        run: |
          make
          cp ./build/teal .
          teal ./cmd/main.go

      - name: Install & Test (web/server)
        if: matrix.project != 'cli'
        working-directory: ${{ matrix.project }}
        run: |
          npm install
          echo "No tests yet for ${{ matrix.project }}"
